trigger:
  branches:
    include:
    - main

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: BuildAndPackage
  jobs:
  - job: Build
    steps:
    - checkout: self
    - task: UseNode@1
      inputs:
        version: '18.x'
    - script: |
        npm install
        npm run build
        npm run zip
      displayName: 'Build and Package'

- stage: Deploy
  jobs:
  - job: Deploy
    steps:
    - script: |
        source env.sh
        az functionapp deployment source config-zip --resource-group $MY_RESOURCE_GROUP --name $FUNCTION_APP_NAME --src ./deploy.zip
      displayName: 'Deploy to Azure Function App'
